spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testDB
    username: test
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        highlight_sql: true
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 카카오 로그인 요청 uri
            token-uri: https://kauth.kakao.com/oauth/token # 토큰을 발급받기 위한 uri
            user-info-uri: https://kapi.kakao.com/v2/user/me # 유저 정보를 받아오기 위한 uri
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인 요청 uri
            token-uri: https://nid.naver.com/oauth2.0/token # 토큰을 발급받기 위한 uri
            user-info-uri: https://openapi.naver.com/v1/nid/me # 유저 정보를 받아오기 위한 uri
        registration:
          google:
            client_id: ${GOOGLE_CLIENT_ID}
            client_secret: ${GOOGLE_CLIENT_SECRET}
            redirect_uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID} # REST API Key
            client-secret: ${KAKAO_CLIENT_SECRET} # Client Secret Key
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI} # Redirect URI
          naver:
            client-id: ${NAVER_CLIENT_ID} # Client ID
            client-secret: ${NAVER_CLIENT_SECRET} # Client Secret
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: ${NAVER_REDIRECT_URI} # Redirect URL
            scope:
              - email
              - nickname

    user:
      password: 1
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${smtp.name}
    password: ${smtp.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

springdoc:
  swagger-ui:
    operations-sorter: method

logging:
  level:
    org:
      hibernate:
        sql: debug
        orm:
          jdbc:
            bind: trace

cloud:
  aws:
    s3:
      bucket: ${aws.bucket}
    credentials:
      access-key: ${aws.accessKey}
      secret-key: ${aws.secretKey}
    region:
      static: ap-northeast-2
    stack:
      auto: false



auth:
  jwt:
    issuer: team.sparta.com
    secret: ${jwt.secret}
    accessTokenExpirationHour: 1680