# Action 이름
name: 'Build Test'

# Event Trigger : 명시된 branch에 특정 액션(여기서는 Push와 Pull)이 발생했을 때
on:
  # dev 브랜치 또는 feature/ 하위 브랜치가 push 되었을 때
  push:
    branches: [ "dev", feature/* ]
  # dev 브랜치에 PR 요청을 보냈을 때
  pull_request:
    branches: [ "dev" ]

# 실제 어떤 작업을 실행할지에 대한 명시
jobs:
  test:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'

      # 실행 권한 추가
      - name: make executable gradlew
        run: chmod +x ./gradlew

      # clean test 실행
      - name: run test
        run: ./gradlew clean test

  build:
    # 스크립트 실행 환경 (OS)
    runs-on: [ ubuntu-latest ] 

    # 실제 실행 스크립트
    steps: 
      # uses는 github actions에서 제공하는 플러그인을 실행.(git checkout 실행)
      - name: checkout
        uses: actions/checkout@v4

      # with은 plugin 파라미터 입니다. (java 17버전 셋업)
      - name: java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '17'

      # 실행 권한 추가
      - name: make executable gradlew
        run: chmod +x ./gradlew

      # clean build 실행 (테스트 제외)
      - name: run build
        run: ./gradlew clean build -x test