# Action 이름
name: CI-Push

# Event Trigger : 명시된 branch에 특정 액션(여기서는 Pull)이 발생했을 때
on:
  push:
    branches: [ "dev", "feature/*" ]

# 실제 어떤 작업을 실행할지에 대한 명시
jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Gradle 캐싱
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle 명령 실행을 위한 권한을 부여
        run: chmod +x ./gradlew

      - name: Gradle build를 수행
        run: ./gradlew clean build
